shamefullyHoist: true

catalogs:
  dev:
    '@vitejs/plugin-vue': ^5.2.3
    typescript: ^5.8.3
    vite: ^6.3.4
  lint:
    '@antfu/eslint-config': ^4.12.0
    '@vue/tsconfig': ^0.7.0
    eslint: ^9.26.0
    eslint-plugin-format: ^1.0.1
    vue-tsc: ^2.2.10
  prod:
    '@nuxt/ui-pro': ^3.1.1
    pinia: ^3.0.2
    pnpm-workspace-yaml: ^0.3.1
    vue: ^3.5.13
    vue-router: ^4.5.1
  types:
    '@types/node': ^22.15.3

onlyBuiltDependencies:
  - esbuild
