name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - run: npm install -g corepack@latest
      - run: corepack enable
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm build
        env:
          NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}
          VITE_APP_TITLE: ${{ env.VITE_APP_TITLE }}
      # - run: pnpm typecheck # check #5
